export const START_ADD_ITEMS = '@POSTS/START_ADD_ITEMS';
export const ADD_ITEMS = '@POSTS/ADD_ITEMS';
export const ADD_ITEMS_ERROR = '@POSTS/ADD_ITEMS_ERROR';

export const START_ADD_ITEM = '@POSTS/START_ADD_ITEM';
export const ADD_ITEM = '@POSTS/ADD_ITEM';
export const ADD_ITEM_ERROR = '@POSTS/ADD_ITEM_ERROR';

export const START_REMOVE_ITEM = '@POSTS/START_REMOVE_ITEM';
export const REMOVE_ITEM = '@POSTS/REMOVE_ITEM';
export const REMOVE_ITEM_ERROR = '@POSTS/REMOVE_ITEM_ERROR';

export const START_UPDATE_ITEM = '@POSTS/START_UPDATE_ITEM';
export const UPDATE_ITEM = '@POSTS/UPDATE_ITEM';
export const UPDATE_ITEM_ERROR = '@POSTS/UPDATE_ITEM_ERROR';
