export const START_LOAD_ITEMS = '@POSTS/START_LOAD_ITEMS';
export const ADD_ITEMS = '@POSTS/ADD_ITEMS';
export const LOAD_ITEMS_ERROR = '@POSTS/LOAD_ITEMS_ERROR';

export const START_LOAD_ITEM = '@POSTS/START_LOAD_ITEM';
export const ADD_ITEM = '@POSTS/ADD_ITEM';
export const LOAD_ITEM_ERROR = '@POSTS/LOAD_ITEM_ERROR';

export const START_REMOVE_ITEM = '@POSTS/START_REMOVE_ITEM';
export const REMOVE_ITEM = '@POSTS/REMOVE_ITEM';
export const REMOVE_ITEM_ERROR = '@POSTS/REMOVE_ITEM_ERROR';

export const START_UPDATE_ITEM = '@POSTS/START_UPDATE_ITEM';
export const UPDATE_ITEM = '@POSTS/UPDATE_ITEM';
export const UPDATE_ITEM_ERROR = '@POSTS/UPDATE_ITEM_ERROR';
