export const AUTHENTICATE_USER = '@USERS/AUTHENTICATE';
export const UNAUTHENTICATE_USER = '@USERS/UNAUTHENTICATE';

export const START_ADD_ITEM = '@USERS/START_ADD_ITEM';
export const ADD_ITEM = '@USERS/ADD_ITEM';
export const ADD_ITEM_ERROR = '@USERS/ADD_ITEM_ERROR';

export const START_UPDATE_ITEM = '@USERS/START_UPDATE_ITEM';
export const UPDATE_ITEM = '@USERS/UPDATE_ITEM';
export const UPDATE_ITEM_ERROR = '@USERS/UPDATE_ITEM_ERROR';
